### ISSUE TITLE
Getting Bad Gateway after upgrade from version pro:6.3.7 to pro:6.3.9

### ISSUE THREAD

**Issue by satheras** [haiwen/seafile-docker#135] opened 2019-01-13 09:40 UTC
Dear Community,

since Version 6.3.9 i cannot connect to the seafile backend. I get an error from nginx
![seafile error](https://user-images.githubusercontent.com/36051167/51083641-d2d25180-171d-11e9-81e4-3cc4c241aa43.PNG)

if i switch back by using 
image: docker.seadrive.org/seafileltd/seafile-pro:6.3.7 everything works again.

my seafile docker instance was created at 2019-01-13 10:23:54. 

Thats what i can see from the logfiles:

mysql.log: 
> 2019-01-13 10:32:13 139724016487552 [Note] /usr/sbin/mysqld (mysqld 10.1.34-MariaDB-0ubuntu0.18.04.1) starting as process 5711 ...
> 2019-01-13 10:32:13 139724016487552 [Warning] Can't create test file /var/lib/mysql/baa49ee3c7af.lower-test
> 2019-01-13 10:32:13 139724016487552 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
> 2019-01-13 10:32:13 139724016487552 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
> 2019-01-13 10:32:13 139724016487552 [ERROR] Plugin 'Aria' init function returned error.
> 2019-01-13 10:32:13 139724016487552 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
> 2019-01-13 10:32:13 139724016487552 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.

The errors will show up again every few seconds... therefore mysql tries over and over again.

seahub.log:
-----no corresponding enrties for 2019-01-13 10:23:54------

seafile.log

> [01/13/2019

 10:22:59 AM] size-sched.c(103): Repo size compute queue size is 0

seafevents.log:
-----no corresponding enrties for 2019-01-13 10:23:54------

index.log:
-----no corresponding enrties for 2019-01-13 10:23:54------

As far as i can see there is a problem with mysql. But again - if i switch back to 6.3.7. everything works like a charm again. I think there is a problem within the update procedure. Maybe some directories arent existing anymore in the new seafile docker versions ?! Whats about the mysql errors from shown above (e.g.: /var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")). The problems cause is from my point of view mysql related because seafile is not starting up (no running processes, and log entries as you can see)

Maybe it has to do with the base image upgrade to ubuntu base:18.04 within the pro.6.3.9 docker version?

Can you help me please out? 

I propose that others will experience the same problem on their environments by using seafile-pro:latest .

with best regards satheras

**Comment by Dehalion** [comment] 2019-01-29 22:06
The same problem exists with `seafileltd/seafile:6.3.4`, going back to 6.3.3 fixed it again.

Seems to be a permission problem preventing MariaDB to access its data and log files.

**Comment by Fmancino** [comment] 2019-01-29 22:57
duplicate of: https://github.com/haiwen/seafile-docker/issues/77 ?

**Comment by renfeipeng** [comment] 2019-01-30 03:54
This problem is caused by the difference in MySQL's uid between the two docker-images.

You can try:
```bash
sudo docker exec Seafile-Name rm /var/lib/mysql/tc.log
sudo docker exec Seafile-Name chown -R mysql.mysql /var/lib/mysql/
sudo docker restart Seafile-Name
```

**Comment by satheras** [comment] 2019-01-30 15:47
That solved my problem. 

As you can see the ids for the mysql users and groups truly switched. I´ll bet thats caused by doing the ubuntu upgrade on the seafile docker image. There should be a "self healing" routine added to the docker image.

Or other solution: switch seafile from a "one container does it all" to a multiple container approach.

Thanks for the help! I rather would not close this issue since its just a workaround. It will come probably again with the next os and id switch...

here we can see the switched id´s:
![seafile error fix](https://user-images.githubusercontent.com/36051167/51993238-af91fb00-24ae-11e9-9af2-202e0cc2ff56.PNG)

**Closed** 2019-01-31 01:15 UTC
